### ISSUE TITLE
move appending of dom to constructor

### ISSUE THREAD

**Issue by thepassle** [thepassle/generic-components#12]
Not sure why I even did this in connectedCallback, but it should be done in the constructor.

**Comment by thepassle** [comment]
fixed in https://github.com/thepassle/generic-components/commit/1a69e1794d9ddc56b2f3d4dd1775fff8a17fa093

**Comment by vaiil** [comment]
@thepassle There are one more problem: connectedCallback dublicates event listeners. It breaks components. 
For example, run this code on https://modest-bhaskara-e8742f.netlify.app/generic-switch/demo/index.html:
```javascript
function wrap(el, wrapper) {
    el.parentNode.insertBefore(wrapper, el);
    wrapper.appendChild(el);
}
wrap(document.querySelector('.demo'),document.createElement('div'));
```
First switch controll won't work.
