### ISSUE TITLE
disabled switch is not exposed correctly

### ISSUE THREAD

**Issue by scottaohara** [thepassle/generic-components#3]
the `disabled` attribute can only be used on native html controls that allow the attribute.  To properly expose the disabled switch you would need to use `aria-disabled="true"`.

**Comment by thepassle** [comment]
Good catch! Thanks for reporting

**Comment by thepassle** [comment]
Fixed in https://github.com/thepassle/generic-components/commit/818929b047426753e476881c77b36130cd730808
