### ISSUE TITLE
[switch] disable text selection on label double click

### ISSUE THREAD

**Issue by thepassle** [thepassle/generic-components#37]
![dblclick](https://user-images.githubusercontent.com/17054057/94337938-8365af00-ffee-11ea-92c1-3565718fb8db.gif)

**Comment by jsgiant** [comment]
I will do this

**Comment by arnabsen1729** [comment]
Hey @thepassle , Can I work on this ?

**Comment by thepassle** [comment]
You'll have to check with @jsgiant , not sure if he already started on it 🙂

**Comment by jsgiant** [comment]
Hey @arnabsen1729 , I didn't start this yet. You can work on this. Cheers :+1:

**Comment by arnabsen1729** [comment]
@jsgiant sure. Okay @thepassle so I am working on it. :)

**Comment by arnabsen1729** [comment]
@thepassle I am sorry, I am having a hard time to understand

**Comment by trystan2k** [comment]
@arnabsen1729 

One possible solution could be add a new style to the label (adding a .label class to it) with `user-select:none`

Something like this:

```
      .label {
        user-select: none;
      }

     <label part="label" class="label"><slot></slot></label>
```

Please @thepassle, correct me if this is not the correct way.
