### ISSUE TITLE
Fundamental principles of PE/Fallback

### ISSUE THREAD

**Issue by bkardell** [thepassle/generic-components#38]
As several of us discussed yesterday, specifically WRT collaborating here together on tabs, I would love for us to try to first on some more fundamental principles about PE/Fallback, since we have different approaches at different times and it's easy to wind up with different challenges -- so I'm kind of breaking this out, but it definitely informs #10 

Here are 3 that I care about and tried to articulate that it would be good to align on.  I suggest we start by trying to use thumbsup/down to register simple agreement or disagreement and comments to debate if/where necessary. Here is what I propose.
 
## Content must be meaningful when there is no support for whatever reason
We should make sure that whatever elements we use inside don't somehow lose their meaning (it is possible to mess up what is exposed to AT or rely on something which is in fact not well supported) or important aspects of styling

## This content should try to avoid being 'unnatural'
That is, it should reflect the kind of content someone would actually write and consume anyway.  An example of this might be that a tabset composed of a 'toc' style list of links followed by a series of divs.  While this has interesting qualities, without more to the pattern it means that they only retain their relationships in _some_ circumstances and  is probably unnatural if not improved.  That is, normally, discrete sections are demarcated somehow in text (sections, generally have headings which label them). If, in their non-improved state, they instead flow together with no label demarcation, that content is unnatural to consume and can lead to confusion. Imagine "famous quotes on {topic}" in which each tab contains quotes.  In a non-upgraded state, we would see links to sections but it would be impossible to read and attribute them to their orators.  In a simple HTML document, it would be more natural to give these headings or some label.  We should consider these things with care, if we agree that is important.

## We should use care not to actively mislead if things are not upgraded
Examples of this would be using aria roles which won't work unless the upgrade happens or buttons which won't work unless the upgrade happens.  These things leave the consumer in a misleading 'half-way' state.  If, for example, we are creating something that toggles visibility of something, the non-upgraded state should neither hide information, nor convey in any way (via style, element or role) that you can act on it... unless we can fall back to something built in entirely (summary details is native enough to do this now, for example, though that's another discussion)

wdyt? 

cc / @thepassle @jonathantneal @LJWatson @matthewp @davatron5000 @zachleat

**Comment by thepassle** [comment]
The more I think about it, the more sense the following makes to me:

```html
<generic-tabs>
  <h2 slot="tab">John</h2>
  <div slot="panel">My name is John</div>
  <h2 slot="tab">Mark</h2>
  <div slot="panel">My name is Mark</div>
</generic-tabs>
```

If not enhanced, it'll just be headings and 'content' divs (maybe some other element is more semantic than divs here in relation to tabs?). But if JS _is_ enabled, we can give them the correct and required aria roles/states etc.

Technically, the dom order of the content inside the `<generic-tabs>` doesnt matter, because if upgraded, the tabs component will put them in their respective slots, but if there's no JS enabled, it'll just show `h2`, `div`, `h2`, `div`.

This does however rely on the user providing the correct heading levels inside the tab, to maintain a logical heading order for the page.

**Comment by thepassle** [comment]
In the spirit of open-ui, here's some tabs from other component libraries:

[React bootstrap](https://react-bootstrap.github.io/components/tabs/)
![bootstrap](https://user-images.githubusercontent.com/17054057/94917173-5282ef80-04b0-11eb-9b6c-65a376727613.gif)

[Microsoft FAST](https://explore.fast.design/components/fast-tabs)
![fast](https://user-images.githubusercontent.com/17054057/94917192-60387500-04b0-11eb-861b-c8f1a5a04f36.gif)

[Material](https://material-components.github.io/material-components-web-components/demos/tabs/)
![material](https://user-images.githubusercontent.com/17054057/94917213-6c243700-04b0-11eb-9283-3bd87bd95c1a.gif)

[Reach UI](https://reach.tech/tabs/)
![reach](https://user-images.githubusercontent.com/17054057/94917245-7a725300-04b0-11eb-860e-fac396781c91.gif)

[Vaadin](https://vaadin.com/components/vaadin-tabs)
![vaadin](https://user-images.githubusercontent.com/17054057/94917316-9aa21200-04b0-11eb-929e-e3b747063f5a.gif)

**Comment by matthewp** [comment]
My perspective here is that a native tabs element doesn't have a worry about FE, so we shouldn't worsen the design of a tabs component with problems that a native element doesn't have.

**Comment by bkardell** [comment]
I would suggest that this is why I wanted to separate the two conversations.  Some people are interested in exploring this component and hearing feedback and discussion --- that may or may not be useful to standardization too.  Personally, I think that until everyone is shipping, and every user agent supports it, it seems useful anyways so I think it could be good still - but I'm not (currently/with nothing but my own thoughts and no data) willing to represent that in openui as something I have strong feels about.

**Comment by matthewp** [comment]
Yeah there might be 2 parallel discussions to be had where this one informs but doesn't totally align with the openui one. That seems ok to me.

Shouldn't jump to far ahead as the PE concerns necessary for a WC don't necessarily misalign with a built-in future element.

**Comment by matthewp** [comment]
Back to the subject @thepassle, I've seen other tabs implementations like the one you show where the tab and content are siblings with no connection to each other and I find it a bit odd. As with a `label` I would expect a `for` attribute to link think.

Otherwise I would expect a common parent element to represent one tab/content pairing.

**Comment by thepassle** [comment]
> Back to the subject @thepassle, I've seen other tabs implementations like the one you show where the tab and content are siblings with no connection to each other and I find it a bit odd. As with a label I would expect a for attribute to link I think.

The idea is that if JS is enabled, and the tabs component is upgraded, it can set the correct aria roles, controls etc, and to assistive tech it'll be a 'real' tabs. So it gets 'enhanced' if JS is enabled. But if JS is not enabled, it just falls back to being headings and divs.

I feel like this is better than having the 'tab headings' be button elements, because currently if JS isnt enabled, there'll be a button that doesnt really do anything

**Comment by jonathantneal** [comment]
I hope it’s all right if I put some thoughts here, not necessarily aware of what’s been discussed between threads.

In the case of summary details, any element that is not the summary becomes the “body” of details. Applying this idea to tabs is trickier, because we are dealing with a sequence of summary/detail-like relationships rather than a singular one.

There is something between a concept and an implementation detail in HTML where ideas are grouped with minimal surface. This keeps HTML minimal and simple to conceptualize and write, and conceptually loose enough to let many similar but different concepts be communicated with similar mechanisms. This often results in a side effect of communicating depth linear. For example, when a heading is followed by non-heading siblings, a conceptual grouping is implied around both the heading and the “body” siblings that doesn’t exist structurally. In a similar way. This is similar to the lack of a container around the “body” of a details element.

To me, a tabs solution involves this same cross section of concepts and implantation details.

Initially, I settled with dt and dd elements because it made the panel “body” explicit.  After speaking with Léonie, I shifted to “it should be headings and something else”. I think this shift is more meaningful than dt/dd as content, and it provides a stronger fallback. The “something else” could probably be anything, including a sequence of elements or text; that is until the next sibling heading is encountered.

Now, headings in HTML introduce a bit of a problem, because they can be created without tags by using the role attribute, and because they can have levels, implying a possibility that the level is a contributing factor to whether it starts a new tab. This seems like an implementation problem, but I think it crosses into something deeper because of how grouping is conceptualized in HTML.

**Comment by matthewp** [comment]
I'm not sure why we need to have a slot or an element for the heading at all. Given we have parts now isn't passing the heading text via an attribute and then styling parts sufficient?

What is the use case for more complex HTML? Are we ok with people putting weird stuff into the tab heading; a login form, an iframe youtube video, another tab group component?

**Comment by bkardell** [comment]
@matthewp ...Again, I would really like to be careful about keeping these two things a little separate for now: what is this component vs the open-ui discussion.  In this repo, the people who have agreed to collaborate on a custom element are interested in basing this on a PE approach and seeing if people find that useful.  So for this issue, at least, I think think the question of an attribute can be taken off the table.  An attribute has no meaning at all nor is it displayed if it is not supported or script fails so it's kind of a non-starter.

That said, what I can relate beyond this repo from past discussion and experience to the open-ui effort: I definitely get where you are coming from, this was my initial shape in [our 2015/16 proposal too](https://bkardell.com/common-panel/index.src.html), but after much discussion and open issues I was convinced to change that.  I'll try to reflect those over in that repo as we discuss and link to some past discussions - but, basically: attributes for text don't degrade gracefully, they don't support the ability to add things for internationalization, doing several classes of very useful, even common things just isn't possible.

**Comment by jonathantneal** [comment]
> I'm not sure why we need to have a slot or an element for the heading at all. Given we have parts now isn't passing the heading text via an attribute and then styling parts sufficient?

If I understand this correctly, using an attribute would mean the heading is communicated as an attribute and not as rendered content, which I would not agree with. I would expect the rendered content of a tab (_the control part_) to be expressed as rendered content, and not as an attribute (_which I consider to be a configuration, and I say this in knowing defiance of how form elements work_).

> What is the use case for more complex HTML?

While the native tab should not care or dictate much about this, an example for more complex would be adding an `<svg>` icon beside text, or adding a `<button>` element that closes/removes the tab. To be more ambiguous, I think rendered content should be allowed to be rich whenever possible.

**Comment by matthewp** [comment]
Point taken, the discussion about attribute vs. content more belongs in the open-ui threads, I can understand why a content is definitely needed for a PE focused component.

**Comment by bkardell** [comment]
So I see at least 3 people who like the heading/section thing specifically I think, but do we agree the principles above are a good articulation of why?  As silly as this might sound, I believe articulating the principles here is valuable because there might even be better elements or ideas but articulating the principles gives us a context in which to discuss them... It also gives us a thing to test/point to in larger standards discussions if we get there without getting overly prescriptive or distracted.

**Comment by jonathantneal** [comment]
> Content must be meaningful when there is no support for whatever reason

Yes. I mostly agree with this principle. In the case of `<details>`, the `<summary>` element provided no meaningful fallback. If the reasoning was something like “_authors can insert their own meaning, like `<summary><h3 /></summary>`, then I would want to know if we would consider similar solutions as acceptably _meaningful_. I’m under the impression we might not think `<details><summary /><details>` got it “_right_”, given the previous comments in this thread.

> This content should try to avoid being 'unnatural'

Yes. I strongly agree with this. Conceptually, in any panel-like component labels represent an activators (_like tabs_), I think the most naturally representation is where the label is adjacent and prior to its contents.

> We should use care not to actively mislead if things are not upgraded

Yes. I think this aligns well with my previous expectations. To make them more clear, I think _actively misleading_ would be qualified by a solution which uses HTML elements, text, and/or  ARIA attributes to communicate the qualities of a component that do not necessarily exist without the successful runtime of some other CSS or JS.

**Comment by bkardell** [comment]
> Yes. I mostly agree with this principle. In the case of `<details>`, the `<summary>` element provided no meaningful fallback. If the reasoning was something like “_authors can insert their own meaning, like `<summary><h3 /></summary>`, then I would want to know if we would consider similar solutions as acceptably _meaningful_. I’m under the impression we might not think `<details><summary /><details>` got it “_right_”, given the previous comments in this thread.

Well [hixie actually suggested that putting headings in summary was bad](https://lists.w3.org/Archives/Public/public-whatwg-archive/2011Jan/0098.html), but you also would have to decouple that this was in 2011 and all the stuff about the document outline turned out to be wrong, etc as well as the fact that this is simple parent child, unlike summary/details.   In any case, yes I am suggesting that summary details could have been better like this - and no other control that I can think of in HTML passes this test either.  That's not to say plenty of people don't wish we could go back and make them.

**Comment by bkardell** [comment]
So, we just had another meeting, this time including @zachleat and we agreed that these principles seem pretty good and that for tabs at least the pattern of headings/content seems good... _Ideally_...

```
<generic-tabs>
  <h2>John</h2>
  <p>My name is John</p>
  <h2>Mark</h2>
  <p>My name is Mark</p>
</generic-tabs>
```

Where `<h2>` is any heading element (maybe also to support something that has valid aria-heading/level) and `<p>` is really pretty much any normal mostly meaningless child element(s) that follow.  `<generic-tabs>` would just add the slots for you dynamically if they weren't present (you can't really prevent someone from adding them either).  I guess anyone could send a PR to change this at this point - I'm kind of swamped in the very immediate time frame, but if it sits too long I'll get around to it :)

**Comment by matthewp** [comment]
@bkardell Sorry I missed the meeting, but are we saying that the pattern is any 2 elements? Or does the first element have to be an `h` of some sort?

**Comment by bkardell** [comment]
1 is correct. The only caveat, as I said we might also want to _consider_ also support something that identifies as the same with aria.

2 is yes in terms of implementation here.. I think that most elements people would inuit there are fine, but in practice there are probably some things it just shouldn't be.  Like, it shouldn't shouldn't itself be an interactive element, probably, or something that doesn't render. If we wanted this to be a proposal for HTML, we'd need to get more specific on that I guess, but it would also support simple text runs/non marked paragraphs like summary/details too which we shouldn't try to do either imo.

**Comment by matthewp** [comment]
Are there other elements in HTML that expect a certain structure of children but do not expect specific elements like this? My initial thought is the rules seems a little complex and possibly hard to remember.

Unrelated but for (1) it would be nice of `<hgroup>` were also accepted.

**Comment by thepassle** [comment]
So in the example you gave:

```html
<generic-tabs>
  <h2>John</h2>
  <p>My name is John</p>
  <h2>Mark</h2>
  <p>My name is Mark</p>
</generic-tabs>
```

Do we not make use named slots, then? I do feel like slots have a really good usecase here and could probably save some 'internal work' of the tabs component.

Also, in terms of 'allowing' heading elements (or elements with a heading role/aria-level), what do we do if an element is _not_ a heading? e.g.:

```html
<generic-tabs>
  <section>not a heading</section>
  <p>content</p>
  <h2>is a heading</h2>
  <p>more content</p>
</generic-tabs>
```

**Comment by bkardell** [comment]
> Do we not make use named slots, then? 
We do, they are just able to be added dynamically.  Yes, it is a little more work to add them, but there seemed to be agreement they shouldn't _have_ to.  As I said, nothing really prevents authors from adding them themselves either if they find that somehow better.

> Also, in terms of 'allowing' heading elements (or elements with a heading role/aria-level), what do we do if an element is not a heading? e.g.:

I mean, good things won't happen is, I guess the short answer.  Just as your non-upgraded HTML content won't be good to start with, your tabs won't be good either.  I guess I would suggest that anything before the first heading just isn't projected, but yeah, I guess we can dig into specifics.

**Comment by thepassle** [comment]
> We do, they are just able to be added dynamically. Yes, it is a little more work to add them, but there seemed to be agreement they shouldn't have to. As I said, nothing really prevents authors from adding them themselves either if they find that somehow better.

So a user could write `<h2 slot="tab">` or just `<h2>`? Isnt that _more_ confusing?

**Comment by bkardell** [comment]
> Are there other elements in HTML that expect a certain structure of children but do not expect specific elements like this? My initial thought is the rules seems a little complex and possibly hard to remember.
> 
> Unrelated but for (1) it would be nice if `<hgroup>` were also allowed.

I'm not sure what you mean - HTML has lots of rules about what is allowed/expected and not.  Can you be more specific? tables and selects are obvious examples that come to mind with very specific rules that are easy/obvious to point to, interactive elements like links generally should not contain other interactive elements like buttons, summary and details have special relationships.  As far as headings, yes, I am suggesting that at a minimum h1-h6, but "anything that makes a good heading according to HTML/ARIA"  seems more complete to me

**Comment by bkardell** [comment]
> > We do, they are just able to be added dynamically. Yes, it is a little more work to add them, but there seemed to be agreement they shouldn't have to. As I said, nothing really prevents authors from adding them themselves either if they find that somehow better.
> 
> So a user could write `<h2 slot="tab">` or just `<h2>`? Isnt that _more_ confusing?

I mean, you can't prevent it any more than you can prevent someone from putting an aria role on these things heading which we will inevitably have to change, right?

**Comment by thepassle** [comment]
We cant prevent people from putting in there whatever they want, but we could just not support 'unslotted' elements. I feel like requiring the slot is a clearer api, is simpler in terms of implementation, and as added bonus denotes some kind of relation/declarative...ness? for something being a tab or a panel

**Comment by matthewp** [comment]
Am I misunderstanding something but you can only have 1 element per slot name right?

__impl.html__

```html
#shadow
  <slot name="heading"></slot>
```

__usage.html__

```html
<span name="heading">One</span>
<span name="heading">Two</span>
```

I'm not sure what this would do frankly, I would expect it only projects the first into the slot, but I'm not sure. In our case, we only want to project one element into the slot and we want to control which element that is. Am I missing something?

**Comment by matthewp** [comment]
@bkardell 

> I'm not sure what you mean - HTML has lots of rules about what is allowed/expected and not. Can you be more specific? tables and selects are obvious examples that come to mind with very specific rules that are easy/obvious to point to, interactive elements like links generally should not contain other interactive elements like buttons, summary and details have special relationships. 

I guess the thing that's tripping me up about this design is that it is saying:

1. Every __odd__ element must be a heading.

I can only think of rules that apply to __all__ children, I can't think of any elements where rules are applied depending on the index of the element like this.

**Comment by bkardell** [comment]
>  you can only have 1 element per slot name right?
Nope!

**Comment by bkardell** [comment]
> @bkardell
> 
> > I'm not sure what you mean - HTML has lots of rules about what is allowed/expected and not. Can you be more specific? tables and selects are obvious examples that come to mind with very specific rules that are easy/obvious to point to, interactive elements like links generally should not contain other interactive elements like buttons, summary and details have special relationships.
> 
> I guess the thing that's tripping me up about this design is that it is saying:
> 
> 1. Every **odd** element must be a heading.
> 
> I can only think of rules that apply to **all** children, I can't think of any elements where rules are applied depending on the index of the element like this.
> 
> edit: I think there are some elements that have rules about the _first_ element, but again can't think of any using an odd/even pattern like this.

dd, dt?

**Comment by bkardell** [comment]
> We cant prevent people from putting in there whatever they want, but we could just not support 'unslotted' elements. I feel like requiring the slot is a clearer api, is simpler in terms of implementation, and as added bonus denotes some kind of relation/declarative...ness? for something being a tab or a panel

I think it would be great if others from the meeting could weigh in there.  I prefer  you don't have to because on the chance we wanted to explore something like this natively it probably wouldn't use slot attributes but idk...

**Comment by matthewp** [comment]
@bkardell What am I missing? This is displaying both: https://codepen.io/matthewp/pen/jOrdBoK

This is not what we want, right? We want to only display the active tab.

**Comment by bkardell** [comment]
sorry @matthewp I guess I didn't respond to this publicly? Yes, we only want to display the active panel, but that doesn't mean it isn't slotted. Things that are slotted can still be hidden -- this is about, effectively, how you put things in the tree.  See @davatron5000's pr or even the existing impl.

**Comment by bkardell** [comment]
I guess we can close this now?

**Comment by bkardell** [comment]
This issue is closed thanks to @davatron5000's pull, but I was recently reminded of the original attempts to specify tabs back in the early 2000's (removed in 2006's) and it's interesting that hixie had, kind of effectively the same idea - that is, his markup looked almost identical (in fact, I wish that sections had worked out as we imagined all the way back in 91, but alas even after much they aren't everything they could have been)... Anyway, I do kind of wonder if it is worth taking it a little further and trying to support something like his actual proposal which also let you use `<fieldsets>` which is interesting and I hadn't thought of.
