### ISSUE TITLE
tooltip is only available on mouse hover

### ISSUE THREAD

**Issue by scottaohara** [thepassle/generic-components#4]
this pattern doesn't seem done, especially since it's introduced with the quote:
>A tooltip is a popup that displays information related to an element when the element receives keyboard focus ...

Ideally a tooltip would not be used on static text content, and should instead be tied to a focusable element.  Additionally, i'd suggest reviewing WCAG success criterion 1.4.13 and [this article about tooltips and 1.4.13](https://sarahmhigley.com/writing/tooltips-in-wcag-21/) which contains links to custom tooltips

**Comment by thepassle** [comment]
Thanks for reporting!

I have to admit the tooltip implementation was a bit rushed, thats a bad on my part. I'll review the link you sent and improve the implementation. Thanks for these feedbacks btw, its much appreciated 🙂

**Comment by scottaohara** [comment]
there's a reason there's no APG pattern for this.  tooltips are rubbish in general :)

**Comment by thepassle** [comment]
> there's a reason there's no APG pattern for this

I've searched far and wide, and, well, as you already mentioned there dont seem to be any good patterns for this unfortunately (not without needing a bunch of libraries which at this point in time im not willing to do). I've decided to not ship a tooltip element for now, but I might revisit in the future.

**Comment by Malvoz** [comment]
In the case of revisiting this in the future, see development in https://github.com/w3c/aria-practices/issues/127.
