### ISSUE TITLE
tabs (all components maybe?) are racey

### ISSUE THREAD

**Issue by bkardell** [thepassle/generic-components#45]
It seems that if you inline a rollup built script for tabs in blocking fashion in the head (which should be best for actual rendering/perf if you can do it), the shadow dom is created, but tabs actually don't get initialized properly - the result is you get nothing.

See https://codepen.io/bkardell/pen/YzGYMBa for an example/explanation

The custom element life-cycle is tricky... Managing everything through slotchange is really the only way I've found to make all the cases work, but it's not pretty either.

**Comment by thepassle** [comment]
Hrm, thats weird. It currently should already be handled by slotchange, it looks like the slotchange event is not fired when the script is at the top 🤔  It seems to work fine when the script is at the bottom. Even calling `requestUpdate` in the `connectedCallback` doesnt seem to do anything. I'll investigate more tomorrow

**Comment by thepassle** [comment]
Right. There's no default slot. I think adding a `<slot>` after this should work. Will test tomorrow

https://github.com/thepassle/generic-components/blob/b2e080a2c24a45bb58cf98275023079c5a583c5c/generic-tabs/GenericTabs.js#L29
